# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapp', '0002_auto_20181206_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='a_image',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
