# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapp', '0003_auto_20181208_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
