# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-17 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-startime']},
        ),
    ]
