# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('upassword', models.CharField(max_length=20)),
                ('udelete', models.BooleanField()),
            ],
        ),
    ]
