# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 15:25
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='username',
            managers=[
                ('books1', django.db.models.manager.Manager()),
            ],
        ),
    ]
