# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_in', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(null=True),
        ),
    ]
