# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-26 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_in', '0003_auto_20181125_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tocomment', to=settings.AUTH_USER_MODEL),
        ),
    ]
