# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-11-30 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_in', '0004_user_to_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='to_comment',
        ),
    ]
