# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_in', '0007_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='startime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
