# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('bread', models.IntegerField(default=0)),
                ('bcomment', models.IntegerField()),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bookinfo',
            },
        ),
        migrations.CreateModel(
            name='Heroinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=30)),
                ('hgender', models.BooleanField(default=True)),
                ('hcontent', models.CharField(max_length=1030)),
                ('isdelete', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookinfo.Bookinfo')),
            ],
        ),
    ]
